-- ============================================
-- FIX: Add Sample Teachers to teacher_details
-- ============================================
-- Run this in Supabase SQL Editor

-- Insert sample teachers if they don't exist
INSERT INTO teacher_details (
  teacher_id,
  employee_id,
  name,
  date_of_birth,
  gender,
  phone,
  email,
  address,
  city,
  state,
  pincode,
  designation,
  department,
  subject,
  date_of_joining,
  employment_type,
  status,
  highest_qualification,
  university,
  passing_year,
  specialization,
  total_experience_years
) VALUES
(
  'teacher1',
  'teacher1',
  'Dr. Rajesh Kumar',
  '1985-03-15',
  'Male',
  '+91 98765 43210',
  'rajesh.kumar@shivalik.edu',
  '123 Faculty Colony, Dehradun',
  'Dehradun',
  'Uttarakhand',
  '248001',
  'Professor',
  'Computer Science',
  'Data Structures',
  '2015-07-01',
  'Permanent',
  'Active',
  'Ph.D. in Computer Science',
  'IIT Delhi',
  2014,
  'Algorithms & Data Structures',
  10
),
(
  'teacher2',
  'teacher2',
  'Dr. Priya Sharma',
  '1988-06-20',
  'Female',
  '+91 98765 43211',
  'priya.sharma@shivalik.edu',
  '124 Faculty Colony, Dehradun',
  'Dehradun',
  'Uttarakhand',
  '248001',
  'Associate Professor',
  'Mathematics',
  'Calculus',
  '2016-08-15',
  'Permanent',
  'Active',
  'Ph.D. in Mathematics',
  'Delhi University',
  2015,
  'Applied Mathematics',
  9
),
(
  'teacher3',
  'teacher3',
  'Mr. Amit Verma',
  '1990-09-10',
  'Male',
  '+91 98765 43212',
  'amit.verma@shivalik.edu',
  '125 Faculty Colony, Dehradun',
  'Dehradun',
  'Uttarakhand',
  '248001',
  'Assistant Professor',
  'Physics',
  'Quantum Mechanics',
  '2018-01-10',
  'Permanent',
  'Active',
  'M.Sc. in Physics',
  'IIT Roorkee',
  2017,
  'Quantum Physics',
  7
),
(
  'teacher4',
  'teacher4',
  'Ms. Neha Gupta',
  '1992-12-05',
  'Female',
  '+91 98765 43213',
  'neha.gupta@shivalik.edu',
  '126 Faculty Colony, Dehradun',
  'Dehradun',
  'Uttarakhand',
  '248001',
  'Lecturer',
  'English',
  'Literature',
  '2019-07-01',
  'Contract',
  'Active',
  'M.A. in English',
  'Delhi University',
  2018,
  'English Literature',
  6
),
(
  'teacher5',
  'teacher5',
  'Dr. Suresh Patel',
  '1983-04-25',
  'Male',
  '+91 98765 43214',
  'suresh.patel@shivalik.edu',
  '127 Faculty Colony, Dehradun',
  'Dehradun',
  'Uttarakhand',
  '248001',
  'Professor',
  'Chemistry',
  'Organic Chemistry',
  '2012-06-01',
  'Permanent',
  'Active',
  'Ph.D. in Chemistry',
  'IIT Bombay',
  2011,
  'Organic Chemistry',
  13
)
ON CONFLICT (teacher_id) DO UPDATE SET
  employee_id = EXCLUDED.employee_id,
  name = EXCLUDED.name,
  email = EXCLUDED.email,
  phone = EXCLUDED.phone,
  department = EXCLUDED.department,
  designation = EXCLUDED.designation,
  subject = EXCLUDED.subject,
  status = EXCLUDED.status;

-- Verify the data
SELECT teacher_id, employee_id, name, department, subject, status 
FROM teacher_details 
ORDER BY teacher_id;
